// This file was autogenerated by app/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../components/closure-helpers/lib/debug.js', ['ssd.debug'], ['goog.debug', 'goog.debug.FancyWindow', 'goog.debug.LogManager', 'goog.debug.Logger'], false);
goog.addDependency('../../../components/closure-helpers/lib/helpers.js', ['ssd.helpers'], ['goog.array', 'goog.json', 'goog.object'], false);
goog.addDependency('../../../js/app/showcase-debug.js', ['app.Showdebug'], ['goog.debug.FancyWindow', 'goog.debug.LogManager', 'goog.debug.Logger'], false);
goog.addDependency('../../../js/app/ui-events.js', ['app.ui.Debug'], ['app.Module', 'app.Showdebug', 'ssd.debug'], false);
goog.addDependency('../../../js/core/core.js', ['app.Core', 'appOne'], ['app.Module', 'app.ui.Debug', 'goog.events.EventHandler', 'ssd.helpers', 'ssd.invocator'], false);
goog.addDependency('../../../js/core/exports.js', ['app.exports'], ['app.Core', 'app.ajax', 'app.sync', 'appOne'], false);
goog.addDependency('../../../js/core/response.core.js', ['app.Response'], ['goog.events.Event', 'goog.object'], false);
goog.addDependency('../../../js/libs/invocator.js', ['ssd.invocator'], ['goog.object'], false);
goog.addDependency('../../../js/libs/module.js', ['app.Module'], ['goog.events.EventTarget'], false);
goog.addDependency('../../../js/libs/vendor.loader.js', ['ssd.vendor'], [], false);
goog.addDependency('../../../js/main.js', ['app'], ['app.Core', 'app.exports', 'ssd.debug', 'ssd.vendor'], false);
goog.addDependency('../../../js/network/ajax.js', ['app.ajax', 'app.ajax.Method'], ['app.sync.Response', 'goog.Uri', 'goog.net.XhrIo', 'ssd.helpers'], false);
goog.addDependency('../../../js/network/response.sync.js', ['app.sync.Response', 'app.sync.T'], ['app.Response', 'goog.object'], false);
goog.addDependency('../../../js/network/sync.js', ['app.sync'], ['app.ajax', 'app.sync.Response'], false);
